package queries

import (
	"context"
	"fmt"
)

// CreateProduct creates a new product
// Generated by SQLC from products.sql
func (q *Queries) CreateProduct(ctx context.Context, sku string, name string, description *string, price string) (Product, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO products (sku, name, description, price)
		 VALUES ($1, $2, $3, $4)
		 RETURNING id, sku, name, description, price, created_at, updated_at`,
		sku, name, description, price)

	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// GetProductByID retrieves a product by ID
// Generated by SQLC from products.sql
func (q *Queries) GetProductByID(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, sku, name, description, price, created_at, updated_at
		 FROM products
		 WHERE id = $1`,
		id)

	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// GetProductBySKU retrieves a product by SKU
// Generated by SQLC from products.sql
func (q *Queries) GetProductBySKU(ctx context.Context, sku string) (Product, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, sku, name, description, price, created_at, updated_at
		 FROM products
		 WHERE sku = $1`,
		sku)

	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// ListProducts retrieves a paginated list of products
// Generated by SQLC from products.sql
func (q *Queries) ListProducts(ctx context.Context, limit int32, offset int32) ([]Product, error) {
	rows, err := q.db.Query(ctx,
		`SELECT id, sku, name, description, price, created_at, updated_at
		 FROM products
		 ORDER BY created_at DESC
		 LIMIT $1 OFFSET $2`,
		limit, offset)

	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("failed to scan product row: %w", err)
		}
		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating product rows: %w", err)
	}

	return items, nil
}

// SearchProducts searches for products by name or description
// Generated by SQLC from products.sql
func (q *Queries) SearchProducts(ctx context.Context, query string, limit int32, offset int32) ([]Product, error) {
	rows, err := q.db.Query(ctx,
		`SELECT id, sku, name, description, price, created_at, updated_at
		 FROM products
		 WHERE name ILIKE '%' || $1 || '%' OR description ILIKE '%' || $1 || '%'
		 ORDER BY created_at DESC
		 LIMIT $2 OFFSET $3`,
		query, limit, offset)

	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("failed to scan product row: %w", err)
		}
		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating product rows: %w", err)
	}

	return items, nil
}

// UpdateProduct updates a product
// Generated by SQLC from products.sql
func (q *Queries) UpdateProduct(ctx context.Context, id int32, name string, description *string, price string) (Product, error) {
	row := q.db.QueryRow(ctx,
		`UPDATE products
		 SET name = $2, description = $3, price = $4, updated_at = CURRENT_TIMESTAMP
		 WHERE id = $1
		 RETURNING id, sku, name, description, price, created_at, updated_at`,
		id, name, description, price)

	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// DeleteProduct deletes a product
// Generated by SQLC from products.sql
func (q *Queries) DeleteProduct(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, `DELETE FROM products WHERE id = $1`, id)
	return err
}

// CountProducts returns the total number of products
// Generated by SQLC from products.sql
func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, `SELECT COUNT(*) FROM products`)
	var count int64
	err := row.Scan(&count)
	return count, err
}
