package queries

import (
	"context"
	"fmt"
)

// CreateUser creates a new user
// Generated by SQLC from users.sql
func (q *Queries) CreateUser(ctx context.Context, email string, name string, passwordHash string) (User, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO users (email, name, password_hash)
		 VALUES ($1, $2, $3)
		 RETURNING id, email, name, password_hash, created_at, updated_at`,
		email, name, passwordHash)

	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// GetUserByID retrieves a user by ID
// Generated by SQLC from users.sql
func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, email, name, password_hash, created_at, updated_at
		 FROM users
		 WHERE id = $1`,
		id)

	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// GetUserByEmail retrieves a user by email
// Generated by SQLC from users.sql
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, email, name, password_hash, created_at, updated_at
		 FROM users
		 WHERE email = $1`,
		email)

	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// ListUsers retrieves a paginated list of users
// Generated by SQLC from users.sql
func (q *Queries) ListUsers(ctx context.Context, limit int32, offset int32) ([]User, error) {
	rows, err := q.db.Query(ctx,
		`SELECT id, email, name, password_hash, created_at, updated_at
		 FROM users
		 ORDER BY created_at DESC
		 LIMIT $1 OFFSET $2`,
		limit, offset)

	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("failed to scan user row: %w", err)
		}
		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating user rows: %w", err)
	}

	return items, nil
}

// UpdateUser updates a user
// Generated by SQLC from users.sql
func (q *Queries) UpdateUser(ctx context.Context, id int32, name string) (User, error) {
	row := q.db.QueryRow(ctx,
		`UPDATE users
		 SET name = $2, updated_at = CURRENT_TIMESTAMP
		 WHERE id = $1
		 RETURNING id, email, name, password_hash, created_at, updated_at`,
		id, name)

	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// DeleteUser deletes a user
// Generated by SQLC from users.sql
func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, `DELETE FROM users WHERE id = $1`, id)
	return err
}

// CountUsers returns the total number of users
// Generated by SQLC from users.sql
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, `SELECT COUNT(*) FROM users`)
	var count int64
	err := row.Scan(&count)
	return count, err
}
